### ISSUE TITLE
Page in the screenshot

### ISSUE THREAD

**Issue by avigilante** [davidgolding/obsidian-big-sur-aesthetic#5]
Not really an issue, but I'm new to github and don't know how to message someone...
I love the note that you used for the screenshot of your Obsidian theme, but cannot find it anywhere. Any chance you could share it?

**Comment by davidgolding** [comment]
That was one of my personal notes in my Obsidian notebase. I'm afraid I changed my system and no longer use that notebase, and unfortunately, I can't find a backup of the file. Put simply, I had followed a personal knowledge management framework that separated notes by different aspects: Capture, Incubate, Synthesize, and Present. Capturing was the kind of notetaking that occurs when studying or researching or otherwise finding something worth adding to the notebase; these notes served to merely capture ideas and data. Incubating was a different mode of notetaking where new ideas are being generated from captured notes, a kind of open, freethinking exercise of connecting captured notes together. Synthesizing was more serious concentration in building an argument, a thesis, really anything that is a fully formed idea or sequence of ideas. And Presenting was a more final form of writing based on synthesized notes. This system was intended to separate notetaking concerns into their different aspects, meaning, processes that occur discretely over the lives of researching and writing projects. It was a useful system in its own way. I opted for something else because of my own thought patterns and what it's like for me when I encounter data worth annotating or thinking about. Hope this is useful.
